name: Build iOS

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_ios:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 'stable'

      - name: Install dependencies
        run: flutter pub get

      - name: Build for Simulator   # no signing required
        run: flutter build ios --simulator

      - name: Upload Simulator build
        uses: actions/upload-artifact@v2
        with:
          name: wefund-sim-app
          path: build/ios/iphonesimulator/Runner.app
